# Generated by Django 5.0.4 on 2025-03-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_category_category_description_category_icon_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
