# Generated by Django 5.0.4 on 2025-03-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_category_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='mascot_url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
