# Generated by Django 4.2.20 on 2025-03-09 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_category_mascot_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='journallog',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
